"""empty message

Revision ID: 8fc0e1e38466
Revises: 
Create Date: 2018-11-30 12:33:55.866296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc0e1e38466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameRoomID', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('correctAnswer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hostID', sa.Integer(), nullable=True),
    sa.Column('playerCount', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_room_name'), 'game_room', ['name'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('totalSongsPlayed', sa.Integer(), nullable=True),
    sa.Column('totalCorrectGuesses', sa.Integer(), nullable=True),
    sa.Column('monthlySongsPlayed', sa.Integer(), nullable=True),
    sa.Column('monthlyCorrectGuesses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=True)
    op.create_table('player_to_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=True),
    sa.Column('gameRoomID', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trackID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_to_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_to_game')
    op.drop_table('song')
    op.drop_table('player_to_game')
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_room_name'), table_name='game_room')
    op.drop_table('game_room')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
